commit_message: '[Crowdin] Update translations (%language%) %original_file_name%'
append_commit_message: false
files:
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
